# Automação Web e Busca de Informações com Python

#### Desafio: 

Trabalhamos em uma importadora e o preço dos nossos produtos é vinculado a cotação de:
- Dólar
- Euro
- Ouro

Precisamos pegar na internet, de forma automática, a cotação desses 3 itens e saber quanto devemos cobrar pelos nossos produtos, considerando uma margem de contribuição que temos na nossa base de dados.

Base de Dados: https://drive.google.com/drive/folders/1KmAdo593nD8J9QBaZxPOG1yxHZua4Rtv?usp=sharing

Para isso, vamos criar uma automação web:

- Usaremos o selenium
- Importante: baixar o webdriver

In [7]:
from selenium import webdriver 
import pandas as pd
import time
import pyautogui as py
#from selenium.webdriver.common.keys import keys
#from webdriver.common.by import By
#from selenium.webdriver.remote.webelement import WebElement


navegador = webdriver.Chrome()
navegador.get("https://www.google.com.br/")

    
# 1 - Pegar a cotação do dolar
navegador.find_element("xpath",'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação dólar")
# A forma abaixo como mostra no curso, não funcionou
#navegador.find_element("xpath",'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)
# A forma abaixo eu descobri sozinho e funcionou
navegador.find_element("xpath",'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(webdriver.Keys.ENTER)

cotacao_dolar = navegador.find_element("xpath",'/html/body/div[7]/div/div[10]/div/div[2]/div[2]/div/div/div[1]/div/div/div/div/div/div/div/div[3]/div[1]/div[1]/div[2]/span[1]').get_attribute("data-value")
print("Preço dolar: ", cotacao_dolar)

time.sleep(2)

# 2 - Pegar a cotação do Euro
limpar_input = navegador.find_element("xpath",'/html/body/div[4]/div[2]/form/div[1]/div[1]/div[2]/div/div[2]/input')
limpar_input.clear()

time.sleep(2)

navegador.find_element("xpath",'/html/body/div[4]/div[2]/form/div[1]/div[1]/div[2]/div/div[2]/input').send_keys("cotação Euro")
navegador.find_element("xpath",'/html/body/div[4]/div[2]/form/div[1]/div[1]/div[2]/div/div[2]/input').send_keys(webdriver.Keys.ENTER)

cotacao_euro = navegador.find_element("xpath",'/html/body/div[7]/div/div[10]/div/div[2]/div[2]/div/div/div[1]/div/div/div/div/div/div/div/div[3]/div[1]/div[1]/div[2]/span[1]').get_attribute("data-value")
print("Preço Euro: ", cotacao_euro)


# 3 - Pegar a cotação do Ouro
time.sleep(2)

navegador.get("https://www.melhorcambio.com/ouro-hoje")
cotacao_ouro = navegador.find_element("xpath",'/html/body/div[5]/div[1]/div/div/input[2]').get_attribute("value")

# Um ponto em que precisamos prestar atenção é que o Python se utiliza de “.” como divisor das casas decimais. Ou seja,
# ao coletarmos a informação no modelo brasileiro com vírgula ao invés de ponto precisamos alterá-la para como o Python
# enxergará essa informação.
cotacao_ouro = cotacao_ouro.replace(",",".")
print("Preço Ouro: ", cotacao_ouro)
time.sleep(2)
# o comando abaixo fecha o navegador
navegador.quit()

# 4 - Importar a lista de Produtos e atualizar os dados com base nos dados coletados
tabela = pd.read_excel("Produtos.xlsx")
display(tabela)

tabela.loc[tabela["Moeda"] == "Dólar", "Cotação"] = float(cotacao_dolar)
tabela.loc[tabela["Moeda"] == "Euro", "Cotação"] = float(cotacao_euro)
tabela.loc[tabela["Moeda"] == "Ouro", "Cotação"] = float(cotacao_ouro)

display(tabela)

tabela["Preço de Compra"] = tabela["Preço Original"] * tabela["Cotação"]
tabela["Preço de Venda"] = tabela["Preço de Compra"] * tabela["Margem"]
display(tabela)

# 5 - Exportando a tabela para o excel
tabela.to_excel("ProdutosAtualizados.xlsx", index=False)

time.sleep(2)
py.click(x=557, y=750)
time.sleep(1.5)
py.doubleClick(x=347, y=233)

Preço dolar:  5.161957999999999
Preço Euro:  5.088580767000001
Preço Ouro:  276.04

,Produtos,Preço Original,Moeda,Cotação,Preço de Compra,Margem,Preço de Venda
0,Câmera Canon,999.99,Dólar,5,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,6,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,6,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,350,7000.00,1.15,8050.000

,Produtos,Preço Original,Moeda,Cotação,Preço de Compra,Margem,Preço de Venda
0,Câmera Canon,999.99,Dólar,5.161958,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,5.088581,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5.161958,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5.161958,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,5.088581,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5.161958,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,276.040000,7000.00,1.15,8050.000

,Produtos,Preço Original,Moeda,Cotação,Preço de Compra,Margem,Preço de Venda
0,Câmera Canon,999.99,Dólar,5.161958,5161.906380,1.40,7226.668933
1,Carro Renault,4500.00,Euro,5.088581,22898.613452,2.00,45797.226903
2,Notebook Dell,899.99,Dólar,5.161958,4645.710580,1.70,7897.707987
3,IPhone,799.00,Dólar,5.161958,4124.404442,1.70,7011.487551
4,Carro Fiat,3000.00,Euro,5.088581,15265.742301,1.90,29004.910372
5,Celular Xiaomi,480.48,Dólar,5.161958,2480.217580,2.00,4960.435160
6,Joia 20g,20.00,Ouro,276.040000,5520.800000,1.15,6348.920000

### Agora vamos atualiza a nossa base de preços com as novas cotações

- Importando a base de dados

In [3]:
pip install -U selenium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\cce\appdata\roaming\python\python39\site-packages (4.5.0)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\cce\appdata\roaming\python\python39\site-packages (from selenium) (0.9.2)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: trio~=0.17 in c:\users\cce\appdata\roaming\python\python39\site-packages (from selenium) (0.21.0)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: attrs>=19.2.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: outcome in c:\users\cce\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\cce\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\cce\appdata\roaming\python\python39\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\cce\appdata\roaming\python\python39\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)
Note: you may need to restart the kernel to use updated packages.

- Atualizando os preços e o cálculo do Preço Final

In [3]:
time.sleep(5) 
py.position()

Point(x=347, y=233)

### Agora vamos exportar a nova base de preços atualizada